sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

env:
  - TAF_CONFIG=true

install:
  - npm install

script:
  - npm run lint
  - npm test
  - npm run deploy
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push zhengweixu/react-admin
